FROM ubuntu:22.04

RUN ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
RUN apt-get update && apt-get upgrade -y
RUN apt-get install locales locales-all
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN apt-get install -y ninja-build cmake clang clangd clang-format clang-tidy libc++-dev \
  libc++abi-dev python3 python3-pip python-is-python3 git dotnet-runtime-6.0 lcov
RUN ln -s /usr/lib/llvm-14/bin/llvm-cov /usr/bin

RUN pip install conan cmakelang
RUN conan profile detect
