FROM ubuntu:22.04

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y ninja-build cmake clang clangd clang-format clang-tidy libc++-dev \
  libc++abi-dev python3 python3-pip python-is-python3 git dotnet-runtime-6.0
RUN pip install conan cmakelang
RUN conan profile detect
